#!/usr/bin/env python3
"""build.py — regenerate SPINE-TRUE.md + COVERAGE.md from the live Paketti code.

Self-contained (no external repo): runs .spine/harness.lua under luajit to capture
every keybinding / menu entry / MIDI mapping with FULLY-RESOLVED names (for-loops
expanded), then writes:
  • SPINE-TRUE.md  — Paketti's anatomy: where it touches Renoise, by region
  • COVERAGE.md    — the three orifices (keyboard / MIDI / menu) compared; the gaps

Run by the GitHub Action on every push that changes .lua / the changelog.

    python3 .spine/build.py [repo_root]      # default: cwd
"""
import json
import os
import re
import shutil
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path.cwd()
HARNESS = ROOT / ".spine" / "harness.lua"
TMP = ROOT / ".spine" / "spine-true.json"

GROUPS = {
    "Song & pattern": ["PatternEditor", "PatternMatrix", "PatternSequencer",
                       "PhraseEditor", "PhraseGrid", "PhraseMappings"],
    "Samples & instruments": ["SampleEditor", "SampleEditorRuler", "SampleNavigator",
                              "InstrumentBox", "SampleKeyzone", "SampleFXMixer",
                              "SampleModulationMatrix"],
    "Mixing, FX & automation": ["Mixer", "TrackDSPDevice", "TrackDSPChain",
                                "Automation", "TrackAutomationList", "DSPDeviceAutomation"],
    "Files": ["DiskBrowserFiles"],
    "Menus & global": ["MainMenuTools", "MainMenuView", "MainMenuFile", "Global", "Paketti"],
}
_HINT = re.compile(r"\s*[\[<(][^\]\)>]*[\]\)>]\s*$")


def run_harness():
    lj = shutil.which("luajit") or shutil.which("lua")
    if not lj:
        sys.exit("build.py: need luajit (apt-get install luajit)")
    subprocess.run([lj, str(HARNESS), str(ROOT), str(TMP)], timeout=300, check=False,
                   stdout=subprocess.DEVNULL)   # Paketti's load prints are noise here
    if not TMP.exists():
        sys.exit("build.py: harness produced no output")
    return json.loads(TMP.read_text())


def leaf(name):
    s = name.split(":")[-1].lstrip("-").lstrip("!").strip()
    return _HINT.sub("", s).strip()


def region_of(name):
    seg = name.split(":")[0].lstrip("-").lstrip("!").strip()
    return "Global" if seg in ("Paketti", "") else seg


def spine_md(d):
    u, regions, files, psc = d["unique"], d["regions"], d["files"], d.get("paketti_self_counts", {})
    nloaded, nbad, ntot = d["file_stats"]["loaded"], d["file_stats"]["errored"], d["file_stats"]["total"]
    grand = u["keybinding"] + u["menu_entry"] + u["midi_mapping"]

    # cluster totals (live, from the counts) for the plain-language reading below
    def clus(keys):
        return sum(regions.get(k, {}).get(x, 0)
                   for k in keys for x in ("keybinding", "menu_entry", "midi_mapping"))
    g_keys = regions.get("Global", {}).get("keybinding", 0)
    pattern = clus(GROUPS["Song & pattern"])
    samples = clus(GROUPS["Samples & instruments"])
    mixing = clus(GROUPS["Mixing, FX & automation"])

    m = ["# Paketti — the TRUE spine (from the running code)", "",
         "*Auto-generated by `.spine/build.py` (the GitHub Action) — captured by running "
         "Paketti's own registration code under a mocked Renoise; for-loops expanded, "
         "wrappers honoured. Do not hand-edit.*", "",
         "## Where Paketti touches Renoise", "",
         f"- **{grand:,} unique registration points**",
         f"  - **{u['keybinding']:,} keyboard shortcuts**",
         f"  - **{u['menu_entry']:,} menu entries**",
         f"  - **{u['midi_mapping']:,} MIDI mappings**", "",
         f"**Validation:** Paketti's own runtime counters say {psc.get('keybindings',0):,} keybindings "
         f"/ {psc.get('midi_mappings',0):,} MIDI / {psc.get('menu_tally_total',0):,} menus — matching.", "",
         "## What Paketti does for Renoise", "",
         f"Paketti is a **{grand:,}-action layer** bolted onto Renoise. *Where* those actions live "
         "tells you its character:", "",
         f"- **Keyboard- and MIDI-first.** {g_keys:,} shortcuts fire *anywhere* (the Global region) and "
         f"{u['midi_mapping']:,} actions are MIDI-mappable — most of Paketti is reachable without ever "
         "opening a menu. It's built for speed and for hardware.",
         f"- **Pattern-centric.** ~{pattern:,} actions live in the Pattern Editor / Matrix / Sequencer / "
         "Phrase views — the tracker grid where you actually make the music is where Paketti is heaviest.",
         f"- **A sample & instrument powerhouse.** ~{samples:,} actions across the Sample Editor, "
         "Navigator, Keyzone, Mappings and Instrument Box — a whole sampler workflow grafted on.",
         f"- **Menus are the catalogue.** {u['menu_entry']:,} menu entries make every feature browsable "
         "when you don't remember the shortcut.",
         f"- **Lighter, deliberate touch on mixing / FX / automation** (~{mixing:,}) — present, but not "
         "the focus. Paketti augments the tracker and the sampler; it doesn't rebuild the mixer.", "",
         "**In one line:** Paketti turns Renoise into a keyboard- and MIDI-driven, pattern-and-sample-"
         "centric production environment — most of its power reachable instantly from a key or a "
         "controller.", "",
         "## Where the features live (Renoise regions)", "",
         "| Region | shortcuts | menus | MIDI | total |", "|---|--:|--:|--:|--:|"]
    placed = set()
    for grp, keys in GROUPS.items():
        rows = [(k, regions[k]) for k in keys if k in regions]
        if not rows:
            continue
        m.append(f"| **{grp}** | | | | |")
        for k, c in sorted(rows, key=lambda x: -(x[1]["keybinding"] + x[1]["menu_entry"] + x[1]["midi_mapping"])):
            placed.add(k)
            t = c["keybinding"] + c["menu_entry"] + c["midi_mapping"]
            m.append(f"| &nbsp;&nbsp;{k} | {c['keybinding']:,} | {c['menu_entry']:,} | {c['midi_mapping']:,} | {t:,} |")
    other = [(r, c) for r, c in regions.items() if r not in placed]
    if other:
        m.append("| **Other** | | | | |")
        for r, c in sorted(other, key=lambda x: -(x[1]["keybinding"] + x[1]["menu_entry"] + x[1]["midi_mapping"])):
            t = c["keybinding"] + c["menu_entry"] + c["midi_mapping"]
            m.append(f"| &nbsp;&nbsp;{r} | {c['keybinding']:,} | {c['menu_entry']:,} | {c['midi_mapping']:,} | {t:,} |")
    m += ["", f"## Robustness: {nloaded}/{ntot} files load clean, {nbad} brittle", ""]
    if nbad:
        for f in files:
            if not f["ok"]:
                m.append(f"- **{f['module']}** — `{f.get('err','')[:140]}`")
    else:
        m.append("All files load and register without error.")
    return "\n".join(m) + "\n"


def coverage_md(d):
    names = d["names"]
    KB = {leaf(n) for n in names["keybinding"]}
    MI = {leaf(n) for n in names["midi_mapping"]}
    ME = {leaf(n) for n in names["menu_entry"]}
    kb_by, me_by = defaultdict(set), defaultdict(set)
    for n in names["keybinding"]:
        kb_by[region_of(n)].add(leaf(n))
    for n in names["menu_entry"]:
        me_by[region_of(n)].add(leaf(n))
    alla = KB | MI | ME
    buckets = defaultdict(int)
    for a in alla:
        buckets[("K" if a in KB else "") + ("M" if a in MI else "") + ("E" if a in ME else "")] += 1
    label = {"KME": "all three", "KM": "keyboard + MIDI (no menu)", "KE": "keyboard + menu (no MIDI)",
             "ME": "MIDI + menu (no keyboard)", "K": "keyboard ONLY", "M": "MIDI ONLY", "E": "menu ONLY (mouse-only)"}
    m = ["# Paketti — cross-orifice coverage (what's left on the table)", "",
         "*Auto-generated by `.spine/build.py`. The three doors to a feature — keyboard / MIDI / "
         "menu — matched by action name. A feature behind one door is unreachable through the others.*", "",
         f"## {len(alla):,} distinct actions", "", "| reachable by | count | meaning |", "|---|--:|---|"]
    for tag in ["KME", "KE", "KM", "ME", "K", "E", "M"]:
        if buckets.get(tag):
            m.append(f"| **{tag}** | {buckets[tag]:,} | {label.get(tag, tag)} |")
    m += ["", f"- Keyboard {len(KB):,} · MIDI {len(MI):,} · Menu {len(ME):,}",
          f"- **Shortcut but NO MIDI:** {len(KB-MI):,} (controller users can't reach)",
          f"- **Shortcut but NO menu:** {len(KB-ME):,} (undiscoverable by browsing)",
          f"- **Menu but NO shortcut:** {len(ME-KB):,} (mouse-only)", "",
          "## Per region — keyboard shortcuts vs the other doors", "",
          "| Region | shortcuts | also MIDI | also menu | keyboard-ONLY |", "|---|--:|--:|--:|--:|"]
    rows = []
    for region, kbset in kb_by.items():
        rows.append((len(kbset), region, len(kbset & MI), len(kbset & me_by.get(region, set())),
                     len(kbset - MI - me_by.get(region, set()))))
    for nkb, region, am, ae, only in sorted(rows, reverse=True):
        if nkb >= 10:
            m.append(f"| {region} | {nkb:,} | {am:,} | {ae:,} | **{only:,}** |")
    return "\n".join(m) + "\n"


def main():
    d = run_harness()
    docs = ROOT / "docs"
    docs.mkdir(exist_ok=True)
    (docs / "SPINE-TRUE.md").write_text(spine_md(d))
    (docs / "COVERAGE.md").write_text(coverage_md(d))
    TMP.unlink(missing_ok=True)
    u = d["unique"]
    print(f"SPINE-TRUE.md + COVERAGE.md written · {u['keybinding']:,} shortcuts · "
          f"{u['menu_entry']:,} menus · {u['midi_mapping']:,} MIDI · "
          f"{d['file_stats']['loaded']}/{d['file_stats']['total']} files clean")
    return 0


if __name__ == "__main__":
    sys.exit(main())
