#!/usr/bin/env python3
"""dialog-gallery.py — regenerate manual/DIALOG-GALLERY.md from the PNGs on disk.

The gallery table drifts whenever screenshots are added (034, 056, 078, 081, 084, 085 were
captured after the initial 157-shot commit but never made it into the table). This rebuilds the
whole table from manual/dialog-screenshots/*.png so the file is always an exact mirror of disk.

Caption = filename with the NNN_ prefix stripped and underscores turned to spaces.

  python3 .spine/dialog-gallery.py [repo_root]
"""
import sys
from pathlib import Path

PAKETTI = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/Users/esaruoho/work/paketti")
SHOTS = PAKETTI / "manual" / "dialog-screenshots"
GALLERY = PAKETTI / "manual" / "DIALOG-GALLERY.md"


def _caption(stem: str) -> str:
    # 039_OctaMED_Pick_Put_Row -> "OctaMED Pick Put Row"
    body = stem.split("_", 1)[1] if "_" in stem else stem
    return body.replace("_", " ")


def main() -> int:
    pngs = sorted(SHOTS.glob("*.png"), key=lambda p: p.name)
    n = len(pngs)
    lines = [
        "# Paketti Dialogs — Screenshot Gallery",
        "",
        f"{n} clean, window-cropped, lossless screenshots of Paketti dialogs — auto-captured via "
        "PakettiMCP + macOS window-ID capture. Source of truth for the manual, the Gumroad page, "
        "PakettiAskBot dialog attachments, and video production.",
        "",
        "*Regenerated by `.spine/dialog-gallery.py` — never hand-edit; it mirrors "
        "`manual/dialog-screenshots/` exactly.*",
        "",
        "| # | Dialog | Screenshot |",
        "|---|--------|-----------|",
    ]
    for p in pngs:
        stem = p.stem
        num = stem.split("_", 1)[0]
        cap = _caption(stem)
        lines.append(f"| {num} | {cap} | ![{cap}](dialog-screenshots/{p.name}) |")
    GALLERY.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"regenerated DIALOG-GALLERY.md — {n} screenshots")
    return 0


if __name__ == "__main__":
    sys.exit(main())
