#!/usr/bin/env python3
"""vault-to-manual.py — feed the bot's CERTIFIED answers into the manual.

The pakettiaskbot vault's vetted answers ARE Esa's authoritative "what it is" descriptions — exactly
what the auto-generated Experimental.md lacks. This writes them into an
`<!-- AUTO:certified -->…<!-- /AUTO -->` block in manual/Experimental.md (all prose elsewhere left
untouched), so certifying an answer (👍 in #paketti-helper) makes it real, version-controlled docs.

Runs LOCALLY — it reads the Syncthing vault, which GitHub CI doesn't have. Commit the result.

  python3 .spine/vault-to-manual.py [repo_root]
"""
import json
import re
import sys
from pathlib import Path

PAKETTI = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/Users/esaruoho/work/paketti")
MANUAL = PAKETTI / "manual" / "Experimental.md"
README = PAKETTI / "README.md"
VAULT = Path.home() / "work" / "comms" / "queue" / "paketti-faq" / "vault.jsonl"
AUTO_RE = re.compile(r"(<!-- AUTO:certified -->)(.*?)(<!-- /AUTO -->)", re.S)

STARTER = """

---

## ✅ Certified Feature Descriptions

*The maintainer's own authoritative answers, certified via pakettiaskbot (👍 in #paketti-helper).
Regenerated by `.spine/vault-to-manual.py` — never hand-edit between the markers; correct the
certified answer instead.*

<!-- AUTO:certified -->(run vault-to-manual)<!-- /AUTO -->
"""

README_STARTER = """

---

## 🎛️ Flagship Features

*One-line definitions, certified by the maintainer via pakettiaskbot. Auto-generated — see the
[Experimental manual](manual/Experimental.html) for the full write-ups.*

<!-- AUTO:certified -->(run vault-to-manual)<!-- /AUTO -->
"""


def _one_liner(a: str) -> str:
    a = re.sub(r"(?m)^\s*#{1,6}\s+.*$", "", a).strip()        # drop any heading lines
    m = re.match(r"(.+?[.!?])(\s|$)", a.replace("\n", " "))
    return (m.group(1) if m else a[:220]).strip()


def _heading(q: str) -> str:
    h = q.strip()
    h = re.sub(r"(?i)^(what is|what does|what'?s|explain|describe|tell me about|how does)\s+", "", h)
    h = re.sub(r"(?i)\b(in paketti|and what does it do|and what does it)\b", "", h)
    h = re.sub(r"(?i)\bdo\b\s*\??$", "", h).strip(" ?")
    h = re.sub(r"\s{2,}", " ", h)
    return (h[:1].upper() + h[1:]) if h else q.strip()


def main():
    try:
        rows = [json.loads(l) for l in VAULT.read_text(encoding="utf-8").splitlines() if l.strip()]
    except Exception:
        rows = []
    vetted = [e for e in rows if e.get("status") == "vetted"]
    by = {}                               # dedup by heading, last wins
    for e in vetted:
        by[_heading(e.get("q", "")).lower()] = e
    items = sorted(by.values(), key=lambda e: _heading(e.get("q", "")).lower())

    def _ans(a):   # demote any in-answer markdown heading to bold so it doesn't clash with ###
        return re.sub(r"(?m)^\s*#{1,6}\s+(.+?)\s*$", r"**\1**", a.strip())

    body = "\n\n".join(f"### {_heading(e['q'])}\n\n{_ans(e.get('a', ''))}" for e in items) \
        or "_(no certified answers yet)_"

    text = MANUAL.read_text(encoding="utf-8")
    if not AUTO_RE.search(text):
        text = text.rstrip() + STARTER
    text = AUTO_RE.sub(lambda m: f"{m.group(1)}\n{body}\n{m.group(3)}", text)
    MANUAL.write_text(text, encoding="utf-8")
    print(f"synced {len(items)} certified descriptions → manual/Experimental.md")

    # README gets a CONCISE flagship list — feature DEFINITIONS only (skip how-tos), one line each.
    defs = [e for e in items if re.match(
        r"(?i)^(what is|what does|what'?s|explain|describe|tell me about)\b", e.get("q", "").strip())]
    rbody = "\n".join(f"- {_one_liner(e.get('a', ''))}" for e in defs) or "_(none certified yet)_"
    rtext = README.read_text(encoding="utf-8")
    if not AUTO_RE.search(rtext):
        rtext = rtext.rstrip() + README_STARTER
    rtext = AUTO_RE.sub(lambda m: f"{m.group(1)}\n{rbody}\n{m.group(3)}", rtext)
    README.write_text(rtext, encoding="utf-8")
    print(f"synced {len(defs)} flagship one-liners → README.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
