# =============================================================================
# WIKI PAGE / REPORT CARD: Tree menu map generator
#
# WHAT THIS CARD SPAWNS:
#   codespace  — treemenu static Lua menu-registration extractor and menu_items.txt report
#   thinkspace — treemenu.session.md
#   areaspace  — OWNS: generated menu tree inspection output for PakettiAddMenuEntry
#                and renoise.tool():add_menu_entry registrations
#                MUST NOT TOUCH: runtime Renoise menu registration behavior or
#                PakettiMenuConfig preference gates
#
# Report-card legend (grade tags, weakest -> strongest):
#   @designed @built @code-verified @build-verified @sim-verified
#   @runtime-verified @hw-verified   |   @untested @runtime-untested
#   @hw-untested @todo @partial   |   @stock (pre-existing, not ours)
#
# Innards linked back to this card (grep "treemenu"):
#   treemenu - scanner, parser, tree renderer, branch filter
#   runner - repeat runner for refreshing generated reports while editing
#   menu_items.txt - generated complete all-branch report
#
# Commit log:   worktree  Tree menu map generator
# SESSION:      treemenu.session.md
# RESULT:       Feature delivery worktree (direct to main, no PR); card worktree
#
# WATCH: treemenu extract_entries build_report collect_string_constants clean_menu_path
#
# RESULT-LOG >> (auto-maintained by the report-card hooks — newest below)
# =============================================================================

Feature: Tree menu map generator
  As a Paketti maintainer, I want Lua menu registrations rendered as a grouped tree, So that menu organization can be inspected without manually grepping thousands of add_menu_entry calls.

  @shipped @code-verified @runtime-untested
  Scenario: Literal menu registrations become an exact static tree
    # cite: treemenu extract_entries
    # cite: treemenu build_report
    # cite: treemenu format_tree
    Given Lua files contain PakettiAddMenuEntry or renoise.tool():add_menu_entry calls with literal name fields
    When the maintainer runs "./treemenu"
    Then "menu_items.txt" contains an "Exact Static Tree" grouped by colon-separated Renoise menu branch
    And the tree uses visible "|____" depth prefixes for nested branches
    And each leaf prints the full "Root:Folder:Entry" Renoise menu path
    And each leaf cites the source file, line number, and registration API on the same row as the menu path

  @shipped @code-verified @runtime-untested
  Scenario: Separator markers group under the real menu root
    # cite: treemenu clean_menu_path
    Given a menu entry name begins with Renoise's "--" separator marker
    When the tree is generated
    Then the leading marker is stripped before branch grouping
    And the source line is marked with "[separator]"

  @shipped @code-verified @runtime-untested
  Scenario: Dynamic paths are visible without polluting the exact tree
    # cite: treemenu resolve_name_expr
    # cite: treemenu build_report
    Given a menu entry name contains variables or non-static expressions
    When the tree is generated
    Then that registration is listed under "Dynamic / partial registrations"
    And it is excluded from the exact static tree

  @shipped @code-verified @runtime-untested
  Scenario: Simple Lua loops expand into concrete menu rows
    # cite: treemenu expand_name_expr
    # cite: treemenu numeric_loop_values
    # cite: treemenu table_loop_values
    # cite: treemenu table_loop_records
    Given a menu entry name is generated by a simple numeric for-loop, string.format call, or ipairs loop over literal strings or record tables
    When the tree is generated
    Then each generated menu name appears as a concrete exact tree row
    And the source expression is not repeated as an unresolved dynamic entry

  @shipped @code-verified @runtime-untested
  Scenario: One root branch can be inspected alone
    # cite: treemenu main
    Given the maintainer wants to focus on one Renoise menu context
    When they run "./treemenu --branch 'Sample Editor' --output /tmp/sample-editor-menu.txt"
    Then the output contains only registrations below the "Sample Editor" root branch

  @shipped @code-verified @runtime-untested
  Scenario: The report can refresh repeatedly while source files are edited
    # cite: runner
    Given the maintainer is editing Lua menu-registration source files
    When they run "./runner treemenu"
    Then treemenu runs repeatedly until interrupted
    And each new run starts after the previous run finishes and the configured delay elapses
    And the default delay is 5 seconds

  @shipped @code-verified @runtime-untested
  Scenario: Duplicate exact menu paths expose real registration bugs
    # cite: treemenu format_duplicates
    # cite: PakettiMenuConfig.lua Paketti Pattern / Phrase Init Preferences menu registration
    Given two active menu-entry definitions use the same exact Renoise menu path
    When treemenu generates the duplicate exact menu path section
    Then the duplicated path is visible with every source location
    And the source should be deduplicated rather than treated as valid runtime output
